"""add_paper_trades_and_bot_learning_states

Revision ID: c4484b7dc038
Revises: b35efc842fde
Create Date: 2026-05-27 12:08:05.096947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4484b7dc038'
down_revision: Union[str, None] = 'b35efc842fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_learning_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(length=50), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('timeouts', sa.Integer(), nullable=False),
    sa.Column('rolling_accuracy', sa.Float(), nullable=False),
    sa.Column('current_threshold', sa.Float(), nullable=False),
    sa.Column('signal_weights', sa.JSON(), nullable=True),
    sa.Column('sector_accuracy', sa.JSON(), nullable=True),
    sa.Column('regime_accuracy', sa.JSON(), nullable=True),
    sa.Column('mistakes_log', sa.JSON(), nullable=True),
    sa.Column('last_lesson', sa.Text(), nullable=True),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_learning_states_bot_id'), 'bot_learning_states', ['bot_id'], unique=True)
    op.create_index(op.f('ix_bot_learning_states_id'), 'bot_learning_states', ['id'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(length=50), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('WIN', 'LOSS', 'TIMEOUT', 'OPEN', name='tradeoutcome'), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('signal_context', sa.JSON(), nullable=True),
    sa.Column('mistake_analysis', sa.Text(), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('max_hold_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_bot_id'), 'paper_trades', ['bot_id'], unique=False)
    op.create_index('ix_paper_trades_bot_open', 'paper_trades', ['bot_id', 'is_open'], unique=False)
    op.create_index(op.f('ix_paper_trades_id'), 'paper_trades', ['id'], unique=False)
    op.create_index(op.f('ix_paper_trades_is_open'), 'paper_trades', ['is_open'], unique=False)
    op.create_index(op.f('ix_paper_trades_outcome'), 'paper_trades', ['outcome'], unique=False)
    op.create_index(op.f('ix_paper_trades_strategy'), 'paper_trades', ['strategy'], unique=False)
    op.create_index('ix_paper_trades_strategy_outcome', 'paper_trades', ['strategy', 'outcome'], unique=False)
    op.create_index(op.f('ix_paper_trades_symbol'), 'paper_trades', ['symbol'], unique=False)
    op.drop_index('ux_stock_ohlcv_stock_date', table_name='stock_ohlcv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_stock_ohlcv_stock_date', 'stock_ohlcv', ['stock_id', 'date'], unique=True)
    op.drop_index(op.f('ix_paper_trades_symbol'), table_name='paper_trades')
    op.drop_index('ix_paper_trades_strategy_outcome', table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_strategy'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_outcome'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_is_open'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_id'), table_name='paper_trades')
    op.drop_index('ix_paper_trades_bot_open', table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_bot_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_bot_learning_states_id'), table_name='bot_learning_states')
    op.drop_index(op.f('ix_bot_learning_states_bot_id'), table_name='bot_learning_states')
    op.drop_table('bot_learning_states')
    # ### end Alembic commands ###
