"""add_sector_regime_counts_to_bot_learning_state

Revision ID: da6f06da0867
Revises: bcfc8253bec9
Create Date: 2026-05-27 13:05:01.049777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6f06da0867'
down_revision: Union[str, None] = 'bcfc8253bec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_learning_states', sa.Column('sector_counts', sa.JSON(), nullable=True))
    op.add_column('bot_learning_states', sa.Column('regime_counts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_learning_states', 'regime_counts')
    op.drop_column('bot_learning_states', 'sector_counts')
    # ### end Alembic commands ###
